DATASET:
  train_dataset: MView2ShapeNet
  test_dataset: MView2ShapeNet
  n_outpoints: 16384

CONST:
  num_workers: 32
  n_input_points: 3000

NETWORK:
  n_sampling_points: 2048 
  gridding_loss_scales:
    - 128
    - 64
  gridding_loss_alphas:
    - 0.1
    - 0.01
  model_type: "PCF2dNet"
  metric: "emd"
#  encode: "Residualnet"
  encode: "Pointfeat"
#  decode: "Sparenet"
  n_primitives: 32        # 解码器那里控制多少个并行的解码网络，Sparenet的
  decode: "Mviewnet"
  use_adain: "share"
  use_recurefine: false
  use_selayer: true
  use_consist_loss: true

RENDER:
  img_size: 256
  radius_list: 
    - 5.0
    - 7.0
    - 10.0
  n_views: 8

GAN:
  use_im: true
  use_fm: true
  use_cgan: true
  weight_gan: 1.0
  weight_l2: 200
  weight_im: 1
  weight_fm: 1

TRAIN:
  learning_rate: 0.0001
  batch_size: 2
  n_epochs: 150
  save_freq: [1,10,20,30,40,50,60,70,80,90,100,110,120,130,140,145,146,147,148,149,150]
  log_freq: 1

TEST:
# ChamferDistance 或者 EMD
  metric_name: "ChamferDistance"